// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PlatformAuthenticatorPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
private open class PlatformAuthenticatorPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PlatformAuthenticator {
  /**
   * Generates a new key pair in the secure element/keystore.
   * Returns the public key as a 65-byte uncompressed byte array (0x04 || X || Y).
   * Throws if generation fails.
   */
  fun createKey(keyTag: String, callback: (Result<ByteArray>) -> Unit)
  /** Deletes the key associated with the given tag. */
  fun deleteKey(keyTag: String, callback: (Result<Unit>) -> Unit)
  /**
   * Signs the data using the key associated with the given tag.
   * Returns the signature (R || S) bytes.
   */
  fun sign(keyTag: String, data: ByteArray, callback: (Result<ByteArray>) -> Unit)
  /**
   * Retrieves the public key for the given tag.
   * Returns 65-byte uncompressed public key.
   */
  fun getPublicKey(keyTag: String, callback: (Result<ByteArray?>) -> Unit)

  companion object {
    /** The codec used by PlatformAuthenticator. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformAuthenticatorPigeonCodec()
    }
    /** Sets up an instance of `PlatformAuthenticator` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PlatformAuthenticator?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.web3_signers.PlatformAuthenticator.createKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyTagArg = args[0] as String
            api.createKey(keyTagArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PlatformAuthenticatorPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PlatformAuthenticatorPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.web3_signers.PlatformAuthenticator.deleteKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyTagArg = args[0] as String
            api.deleteKey(keyTagArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PlatformAuthenticatorPigeonUtils.wrapError(error))
              } else {
                reply.reply(PlatformAuthenticatorPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.web3_signers.PlatformAuthenticator.sign$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyTagArg = args[0] as String
            val dataArg = args[1] as ByteArray
            api.sign(keyTagArg, dataArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PlatformAuthenticatorPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PlatformAuthenticatorPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.web3_signers.PlatformAuthenticator.getPublicKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyTagArg = args[0] as String
            api.getPublicKey(keyTagArg) { result: Result<ByteArray?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PlatformAuthenticatorPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PlatformAuthenticatorPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
