name: web3_signers
description: A versatile EIP-1271 signature verification package that supports a range of key types—including passkeys, private keys, and seed phrases — enabling secure and flexible on-chain signature verification for any Ethereum-based application.
version: 0.2.0
homepage: https://variance.space
repository: https://github.com/vaariance/web3-signers
issue_tracker: https://github.com/vaariance/web3-signers/issues

environment:
  sdk: ^3.7.0
  flutter: ">=3.24.3"

platforms:
  android:
  ios:
  web:

dependencies:
  passkeys: ^2.9.0
  wallet: ^0.0.18
  web3dart: ^3.0.1
  asn1lib: ^1.6.4
  eip712: ^1.0.0
  cbor: ^6.3.7
  crypto: ^3.0.6

dev_dependencies:
  mockito: ^5.4.4
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

topics:
  - ethereum
  - wallets
  - passkey
