name: web3_signers
description: Web3 signers provides a uniform interface for signing EIP-1271 messages with different EC algorithms.
version: 0.0.5
homepage: https://variance.space
repository: https://github.com/vaariance/web3-signers
issue_tracker: https://github.com/vaariance/web3-signers/issues

environment:
  sdk: ^3.2.6
  flutter: ">=3.16.9"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  asn1lib: ^1.5.2
  passkeys: ^2.0.4
  web3dart: ^2.7.2
  plugin_platform_interface: ^2.1.8
  blockchain_utils: ^2.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

topics:
  - ethereum
  - wallets
  - passkey
  - secure-enclave

flutter:
  plugin:
    platforms:
      android:
        package: com.variance.web3_signers
        pluginClass: SecureP256Plugin
      ios:
        pluginClass: SecureP256Plugin
