name: web3_signers
description: Web3 signers provides a uniform interface for signing EIP-1271 messages with different EC algorithms.
version: 0.1.1
homepage: https://variance.space
repository: https://github.com/vaariance/web3-signers
issue_tracker: https://github.com/vaariance/web3-signers/issues

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.3"

platforms:
  android:
  ios:
  web:

dependencies:
  asn1lib: ^1.5.5
  passkeys: ^2.1.0
  web3dart: ^2.7.3
  blockchain_utils: ^3.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

topics:
  - ethereum
  - wallets
  - passkey
