// Mocks generated by Mockito
import 'package:mocktail/mocktail.dart';
import 'package:passkeys/authenticator.dart';
import 'package:passkeys/types.dart';

class MockPasskeyAuthenticator extends Mock implements PasskeyAuthenticator {}

class FakeAuthenticateRequestType extends Fake
    implements AuthenticateRequestType {}

class FakeRegisterRequestType extends Fake implements RegisterRequestType {}
